### ISSUE TITLE
I cant add websockets to my libgdx project

### ISSUE THREAD

**Issue by dDevTech** [MrStahlfelge/gdx-websockets#2]
I think its a problem related to your maven repository
When i follow the steps to add websockets, for example this line
 compile "com.github.MrStahlfelge.gdx-websockets:core:$wsVersion",
the repository doesnt exist and i get the error
Could not resolve com.github.MrStahlfelge.gdx-websockets:common:1.9.10.3.

**Comment by MrStahlfelge** [comment]
Did you add Jitpack to your repositories?

**Comment by dDevTech** [comment]
Yes.That was the problem. It would be a good idea if you mention it in the wiki because by default libgdx dont add that repository. One question more related to gradle and I would be glad if you respond me. I am using android studio for the html, android, desktop and **SERVER** part. However when i execute the server (gradle task) i cannot run other project because gradle can only execute one task. Is there a way to execute server and client simultanously? When you use websockets in the client side, can you use native java serversocket to connect to the websocket? or you need to also use a special library in the server side?

**Comment by dDevTech** [comment]
Thanks man. You are awesome

**Comment by dDevTech** [comment]
Do you use that library just for the server or for both?

**Comment by MrStahlfelge** [comment]
This library (gdx-websocxkets) for the client, Java-WebSocket for the server
