### ISSUE TITLE
Could not find com.github.MrStahlfelge.gdx-websockets:core:1.1.0.

### ISSUE THREAD

**Issue by ghost** [MrStahlfelge/gdx-websockets#8]
I am pretty new to this and I'm just trying to create a simple websocket without anything else.

My html laucher:
`public class HtmlLauncher extends GwtApplication {

        @Override
        public GwtApplicationConfiguration getConfig () {
                // Resizable application, uses available space in browser
                return new GwtApplicationConfiguration(true);
                // Fixed size application:
                //return new GwtApplicationConfiguration(480, 320);
        }

        @Override
        public ApplicationListener createApplicationListener () {
        		GwtWebSockets.initiate();
                return new GameClass();
        }
}` 

My GameClass:
`public class GameClass extends Game {

	public GameClass() {
		super();
	}

	@Override
	public void create() {
		WebSocket socket = WebSockets.newSocket(WebSockets.toWebSocketUrl("localHost", 8080));
		socket.setSendGracefully(true);
		socket.addListener(new WebSocketListener() {
			@Override
			public boolean onOpen(WebSocket webSocket) {
				System.out.println("Opened!");
				return false;
			}

			@Override
			public boolean onClose(WebSocket webSocket, WebSocketCloseCode code, String reason) {
				// TODO Auto-generated method stub
				return false;
			}

			@Override
			public boolean onMessage(WebSocket webSocket, String packet) {
				// TODO Auto-generated method stub
				return false;
			}

			@Override
			public boolean onMessage(WebSocket webSocket, byte[] packet) {
				// TODO Auto-generated method stub
				return false;
			}

			@Override
			public boolean onError(WebSocket webSocket, Throwable error) {
				// TODO Auto-generated method stub
				return false;
			}
			
		});
		socket.connect();
		
	}

	@Override
	public void render() {
		
	}
}`

My build.gradle:
`buildscript {
    repositories {
    	google() 
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        
    }
    dependencies {
        classpath 'org.wisepersist:gwt-gradle-plugin:1.1.16'
        classpath 'org.gretty:gretty:3.0.7'
    }
}

allprojects {
    apply plugin: "eclipse"

    version = '1.0'
    group = 'com.github.MrStahlfelge.gdx-websockets'
    
    ext {
        appName = "my-gdx-game"
        gdxVersion = '1.10.0'
        roboVMVersion = '2.3.15'
        box2DLightsVersion = '1.5'
        ashleyVersion = '1.7.4'
        aiVersion = '1.8.2'
        gdxControllersVersion = '2.2.1'
    }

    repositories {
        mavenLocal()
        mavenCentral()
        google()
        gradlePluginPortal()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
        maven { url "https://jitpack.io" }
    }
}

project(":desktop") {
    apply plugin: "java-library"

    dependencies {
        implementation project(":core")
        api "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
        api "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
        api "de.golfgl.gdxgamesvcs:gdx-gamesvcs-core-gamejolt:1.1.0"
        api "de.tomgrill.gdxdialogs:gdx-dialogs-desktop:1.3.0"
        api "com.github.MrStahlfelge.gdx-websockets:common:1.1.0"
    }
}

project(":html") {
    apply plugin: "java-library"
    apply plugin: "gwt"
    apply plugin: "war"
    apply plugin: "org.gretty"

    dependencies {
        implementation project(":core")
        api "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion"
        api "com.badlogicgames.gdx:gdx:$gdxVersion:sources"
        api "com.badlogicgames.gdx:gdx-backend-gwt:$gdxVersion:sources"
        api "de.golfgl.gdxgamesvcs:gdx-gamesvcs-core:1.1.0:sources"
        api "de.golfgl.gdxgamesvcs:gdx-gamesvcs-core-gamejolt:1.1.0:sources"
        api "de.tomgrill.gdxdialogs:gdx-dialogs-html:1.3.0"
        api "de.tomgrill.gdxdialogs:gdx-dialogs-html:1.3.0:sources"
        api "de.tomgrill.gdxdialogs:gdx-dialogs-core:1.3.0:sources"
        api "com.github.MrStahlfelge.gdx-websockets:core:1.1.0:sources"
        api "com.github.MrStahlfelge.gdx-websockets:html:1.1.0"
        api "com.github.MrStahlfelge.gdx-websockets:html:1.1.0:sources"
        api "com.github.tommyettinger:jbump:1.0.1:sources"
        api "com.kotcrab.vis:vis-ui:1.4.11:sources"
    }
}

project(":core") {
    apply plugin: "java-library"
    dependencies {
        api "com.badlogicgames.gdx:gdx:$gdxVersion"
        api "de.golfgl.gdxgamesvcs:gdx-gamesvcs-core:1.1.0"
        api "de.tomgrill.gdxdialogs:gdx-dialogs-core:1.3.0"
        api "com.github.MrStahlfelge.gdx-websockets:core:1.1.0"
        api "com.github.tommyettinger:jbump:1.0.1"
        api "com.kotcrab.vis:vis-ui:1.4.11"
        api "com.esotericsoftware.spine:spine-libgdx:3.8.55.1" 
    }
}`

When I run superdev or dist I get the following error:
`> Task :core:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileJava'.
> Could not resolve all files for configuration ':core:compileClasspath'.
   > Could not find com.github.MrStahlfelge.gdx-websockets:core:1.1.0.
     Searched in the following locations:
       - file:/C:/Users/User/.m2/repository/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom
       - https://repo.maven.apache.org/maven2/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom
       - https://plugins.gradle.org/m2/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom
       - https://oss.sonatype.org/content/repositories/releases/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom
       - https://jitpack.io/com/github/MrStahlfelge/gdx-websockets/core/1.1.0/core-1.1.0.pom
     Required by:
         project :core

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org`
What exactly is this and how can I fix it?

**Comment by tommyettinger** [comment]
This seems to be a problem with gdx-setup; I just generated a project with it and it, very strangely, picks 1.1.0 as the version for this library. It seems like no one tested the gdx-websockets option for gdx-setup when it was added?

**Comment by MrStahlfelge** [comment]
Looks like it. I will close this now as it is no issue in this lib :)
